### ISSUE TITLE
Erroneous error message.

### ISSUE THREAD

**Issue by markwelker** [cs340tabyu/cs340Winter2018#260] opened 2018-03-29 01:27 UTC
Error message appears saying "That card is not in the face up deck" occasionally upon an attempt to draw a face up card

Expected:
This error should not ever appear to the user

Steps to Reproduce:
Not 100% sure how I got this. Seems to be an issue with the shuffle feature.
Face up deck had: wild, wild, orange, orange, wild
It would let you select a card and hit OK. Error message would appear, no card added to your hand, and your turn would end.
Selecting from the face down deck fixed this error. Deck shuffled, and you could choose from the face up deck again.
See "not_in_faceup_deck" screenshots for evidence

![not_in_faceup_deck_2](https://user-images.githubusercontent.com/35548890/38064966-0199d460-32be-11e8-9b1c-90cc2bd56f2a.png)
![not_in_faceup_deck](https://user-images.githubusercontent.com/35548890/38064967-01adcb82-32be-11e8-83c8-0152bb727054.png)

**Comment by ephraimkunz** [comment] 2018-03-29 13:53
This was caused by the client and server hands getting out of sync because of a bug with the wrong deck update command being sent. It was fixed with the change made to fix #254.

**Closed as completed by ephraimkunz** 2018-03-29 13:53 UTC
Labels: P3: Affects Gameplay, Team 10
