### ISSUE TITLE
Random breaks

### ISSUE THREAD

**Issue by clairescout** [cs340tabyu/cs340Winter2018#267] opened 2018-03-29 03:18 UTC
Broke when we created a game then backed out then went back in and created another game, then tried to go back out. I'm pretty sure it happened after we had just finished a game. I can't remember exactly, but Jonny was there. It happened another time as well.

**Comment by eschos24** [comment] 2018-03-29 23:47
We have no idea what this means...and obviously can't reproduce it...so....closing it.

**Closed as completed by eschos24** 2018-03-29 23:47 UTC
Labels: P2: Halts Gameplay, Team 2, Could Not Reproduce
